# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.FloatField(db_column='account')),
                ('createDate', models.DateTimeField(db_column='creatDate')),
            ],
            options={
                'db_table': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(db_column='money')),
                ('useTime', models.DateTimeField(db_column='useTime')),
                ('useThing', models.CharField(db_column='useThing', max_length=150)),
            ],
            options={
                'db_table': 'Spend',
            },
        ),
    ]
